apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    run: kuard
  name: kuard
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: kuard
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
       kubernetes.io/change-cause: "Updated image to gcr.io/kuar-demo/kuard-amd64:green"
      creationTimestamp: null
      labels:
        run: kuard
    spec:
      containers:
        - image: gcr.io/kuar-demo/kuard-amd64:green
          imagePullPolicy: IfNotPresent
          name: kuard
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
